In [1]:
from pysus import SIA
import pandas as pd
import os
sia = SIA().load()

/Users/juliasbardelatti/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [3]:
variaveis = [
    "PA_UFMUN", "PA_CMP", "PA_PROC_ID", "PA_NIVCPL", "PA_OBITO", 
    "PA_ENCERR", "PA_PERMAN", "PA_ALTA", "PA_CIDPRI", "PA_CIDCAS", 
    "PA_IDADE", "PA_SEXO", "PA_RACACOR", "PA_MUNPCN", "PA_QTDPRO", 
    "PA_QTDAPR"
]

### Variáveis conforme documentação
- PA_CIDPRI: CID9 Principal (APAC ou BPA-I)
- PA_MUNPCN: Código da Unidade da Federação + Código do Município de residência do paciente ou do estabelecimento,
caso não se tenha a identificação do paciente, o que ocorre no (BPA)
- PA_QTDPRO: Quantidade Produzida (APRESENTADA)

### Variável QTD_PRODUZIDA = 90 para UF - BA para o município 110001

In [4]:
files = sia.get_files("PA", uf="BA", year=2022, month=[5])
parquet = sia.download(files)
df = parquet.to_dataframe()
df = df[variaveis]
#df = df[df['PA_CIDPRI'].str.startswith('I', na=False)]
#df.query("PA_MUNPCN == '110001'")

70678553it [00:00, 71605637092.30it/s]

In [8]:
df['PA_QTDPRO'] = df['PA_QTDPRO'].astype(int)

In [9]:
df.query("PA_MUNPCN == '292010' and PA_PROC_ID == '0401010015'")['PA_QTDPRO'].sum()

169

### Variável QTD_PRODUZIDA = 21 para UF - RO para o município 110001

In [34]:
files = sia.get_files("PA", uf="RO", year=2022, month=[5])
parquet = sia.download(files)
df = parquet.to_dataframe()
df = df[variaveis]
df = df[df['PA_CIDPRI'].str.startswith('I', na=False)]
df.query("PA_MUNPCN == '110001'")

10905950it [00:00, 5589987743.96it/s]

,PA_UFMUN,PA_CMP,PA_PROC_ID,PA_NIVCPL,PA_OBITO,PA_ENCERR,PA_PERMAN,PA_ALTA,PA_CIDPRI,PA_CIDCAS,PA_IDADE,PA_SEXO,PA_RACACOR,PA_MUNPCN,PA_QTDPRO,PA_QTDAPR
11187,110020,202205,0208010025,3,0,0,0,0,I255,0000,061,F,02,110001,1,1
31260,110020,202205,0701010223,0,0,0,0,1,I694,0000,027,F,01,110001,1,1
88423,110020,202205,0208010033,3,0,0,0,0,I255,0000,061,F,02,110001,1,1
295644,110020,202203,0803010010,0,0,0,0,0,I340,0000,026,M,02,110001,18,18

In [30]:
len(df)

775

In [21]:
import datasus_dbc
datasus_dbc.decompress("PARO2205.dbc", "PARO2205.dbf")

In [35]:
from dbfread import DBF
import pandas as pd

dbf = DBF("PARO2205.dbf", encoding="latin-1") 
df = pd.DataFrame(iter(dbf))
df = df[df['PA_CIDPRI'].str.startswith('I', na=False)]
df.query("PA_MUNPCN == '110001'")

,PA_CODUNI,PA_GESTAO,PA_CONDIC,PA_UFMUN,PA_REGCT,PA_INCOUT,PA_INCURG,PA_TPUPS,PA_TIPPRE,PA_MN_IND,...,PA_CODOCO,PA_FLQT,PA_FLER,PA_ETNIA,PA_VL_CF,PA_VL_CL,PA_VL_INC,PA_SRV_C,PA_INE,PA_NAT_JUR
22829,2808412,110000,EP,110020,0000,0000,0000,81,00,M,...,1,S,0,,0.0,0.0,0.0,,,1023
91260,2807092,110000,EP,110020,0000,0000,0000,05,00,I,...,1,K,0,,0.0,0.0,0.0,,,3999
161187,6583202,110000,EP,110020,0000,0000,0000,62,00,I,...,1,R,0,,0.0,0.0,0.0,151001,,2062
295608,6583202,110000,EP,110020,0000,0000,0000,62,00,I,...,1,R,0,,0.0,0.0,0.0,151001,,2062

In [33]:
len(df)

775