In [1]:
import pandas as pd
import requests
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter

/Users/juliasbardelatti/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [14]:
df_junto = pd.read_csv("sih_estrangeiros_2019_2025_filtrado_urgencia.csv")

/var/folders/gy/cxx2_pv95ys52g0qvnjgcsqm0000gn/T/ipykernel_55741/451756362.py:2: DtypeWarning: Columns (88,89,98,99,100,101,102) have mixed types. Specify dtype option on import or set low_memory=False.
  df_junto = pd.read_csv("sih_estrangeiros_2019_2025_filtrado_urgencia.csv")

In [15]:
df_usa = df_junto[df_junto['NACIONAL'] == 36]

In [16]:
df_usa.groupby(['PROC_REA']).size().reset_index(name='Quantidade').sort_values('Quantidade', ascending=False).head(5)

      PROC_REA  Quantidade
108  310010039         123
96   304100021          69
79   303140151          67
196  411010034          60
95   304100013          46

In [20]:
teste = df_usa.query("PROC_REA == 310010039")[['PROC_REA', 'VAL_SH', 'VAL_SP', 'VAL_SADT', 'US_TOT']]
teste

         PROC_REA  VAL_SH  VAL_SP  VAL_SADT  US_TOT
8070    310010039  299.34  255.94         0  137.78
13292   310010039  320.34  255.94         0  101.81
13943   310010039  419.29  275.57         0  120.42
14488   310010039  334.09  275.57         0  112.90
14550   310010039  343.11  175.80         0   98.09
...           ...     ...     ...       ...     ...
198309  310010039  294.60  241.00         0   94.79
205642  310010039  331.34  255.94         0  107.75
205860  310010039  283.60  241.00         0   93.67
206359  310010039  284.60  241.00         0   93.85
207899  310010039  284.60  289.30         0  108.07

[123 rows x 5 columns]